language: java
jdk:
  - openjdk8
script: mvn clean install

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $HEMLIGT
  #github-token: $GITHUB_TOKEN
  file_glob: true
  file: ear/target/mediaserver-ear.ear
  overwrite: true
  on:
    repo: dina-web-nrm/mediaserver-module
    all_branches: true
    tags: true
    
    
# https://docs.travis-ci.com/user/deployment/releases/