
language: java

jdk:
  - openjdk7

sudo: false 

install: true
script: mvn clean install
before_deploy: "Starting deploy"
deploy:
  provider: releases
   api_key:
     secure: 606FGUz1/j5cbF3LMlYayGoFzybkRo5lAWq6cIZZFMcWU6gK2BfJXXHSIf8ycO0XHDxF8drlOuOus3Ji0hw0fR7DWtHnDDahDnx93C7Ku5AMdOQRoqpFiesBJ+p7QYEMoELyYJW1Gf0FYHcuC63VxX6OQ/PYGrFTFLuxWNlz3L/GAu4mw0oE81ykPT7+/iLWw/Q4b+p+L4dpIuvwscW2Cfm/N2wwnPBxB3IE+kKFbU+gbcJodB9o6+NeiZ/Cms0YSYP1RHhFzdYqJJpMcCHE3Jurc5JTq+oBBuIReccTdsnRbA1BBisM7I54WHvUQLyu0hRxmJYrdzdlXhjQUtQJ9S8RShbMW94Q5+40o0DQnw8g5993C2TVy657HNsoJRo1aerMSfIiCxOst2dMdYnORAUMNKdNKNQuYUEntlMzX+UhK5V+dQwewSy01EmgKVz272wM3lIrXZoMvUbwBPRJM0n2tID3Zd7cdfa1M7zlXcw5PXuAbXe8+/SIu6dIMRyAhvNgVgAZdSDgHp/jIBAt9YLzVkT9vnFAWGm/+wP5A7VndLRC3ywgfaLP+6U1G/D7aARHo4FmtWr0ayy56ZLCiVmt3CoERSjumsnvWT+ND7hJ5/6TOOY0Ch3hKDiJaCN5UXgZOHjjHxd3m+skY2twkclwWZOFJqadiI+Mvmse3H4=
  file: /ear/target/mediaserver-ear.ear
  on:
    repo: DINA-Web/mediaserver-module
    all_branches: true
